### ISSUE TITLE
Logseq stopped responding after clicking on the Todo icon from top.

### ISSUE THREAD

**Issue by mgai** [ahonn/logseq-plugin-todo#1]
Hello,

First of all, nice try creating such a plug-in attempting to save us from the tricky queries.

After installing it, I clicked the icon but logseq doesn't respond anymore to any interaction with the program - icon nor page links, anything. When closing logseq window, it showed logseq prompt about internal synching for one second, before it closes.

Restart didn't solve.

To reproduce - 

1. Install the plug in.
2. Click on the plug-in icon from the top.

Tested on logseq-todo-plugin v1.0.0 + Windows 11 + logseq version 0.6.6.

Let me know if you need more logs,
Cheers.

**Comment by ahonn** [comment]
@mgai Please update the plugin to v1.1.2 version. If there is still stopped responding, there should be an error message, please copy it and reply to me for further troubleshooting.

**Comment by mgai** [comment]
Sorry for the late reply as I was bothered by some other stuff. I confirm after upgrading to v1.3.1, the plugin works for me. Great work!
