### ISSUE TITLE
Widget not showing anything

### ISSUE THREAD

**Issue by Microeinstein** [ahonn/logseq-plugin-todo#12]
### Setup
| Description | Value |
| :-- | :-- |
| OS ~ Distro | ArchLinux |
| Locale | IT |
| App version | v0.7.1 |
| App install method | custom repository (tried AppImage) |
| App theme | light built-in |
| Plugin version | v1.3.1 |
| Plugin install method | marketplace |

### Message
Hi, I just installed Logseq and your plugin as described, but I can't get the widget to show up the tasks from journal _nor_ from other pages.
Am I missing something?

Best regards

### Attachments
![screenshot](https://user-images.githubusercontent.com/16826381/171702218-969fa056-c954-44a8-9e88-15483e822b3e.png)

**Comment by ahonn** [comment]
Please enter the following query in logseq and see if it shows the tasks in the current page?

```
#+BEGIN_QUERY
{:title "Find: tagged tasks"
 :query [:find (pull ?b [*])
     :where
     [?b :block/marker ?marker]
     [(contains? #{"NOW" "LATER" "TODO"} ?marker)]
     [?b :block/page ?p]
     (or
       (and
        [?p :block/journal? true]
        [?p :block/journal-day ?d]
        (not [?b :block/scheduled])
        (not [?b :block/deadline])
        [(<= ?d :today)])
       (and
        (or
          [?b :block/scheduled ?d]
          [?b :block/deadline ?d])
        [(<= ?d :today)]))]}
#+END_QUERY
```

**Comment by Microeinstein** [comment]
Tested both in a custom page and the journal — the query correctly detects as specified (journal entries not shown in the screenshot — tested later);
the widget remains empty.

![screenshot](https://user-images.githubusercontent.com/16826381/172135586-befe0065-86aa-45f1-9271-e10cc4769ee9.png)

**Comment by ahonn** [comment]
It looks like something went wrong.
Try opening the console tab in devtools (F12), then click to open the plugin widget and see if there is an error message in the console. Please take a screenshot of what the console shows.

**Comment by Microeinstein** [comment]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> worked for me;
I don't see any errors, I made you a video (notice the brief freeze of developer tools)

https://user-images.githubusercontent.com/16826381/172172886-3fc4db94-8be7-4d5b-845e-b7473683410e.mp4

**Comment by arnefm** [comment]
I'm having the exact same issue. Funny that I'm on Arch Linux too. I've installed Logseq using the logseq-desktop-git package from AUR, so it's completely up to date. The plugin was installed from the marketplace, it's the latest version right now.

**Comment by webbj74** [comment]
I'm experiencing this on Manjaro Linux with KDE Plasma (I also installed Logseq via AUR logseq-desktop-git, and plugin from the Marketplace).

**Comment by webbj74** [comment]
Possible cause? The AUR package [patches package.json](https://aur.archlinux.org/cgit/aur.git/tree/build.patch?h=logseq-desktop-git) to change the electron version from v15.x to v17.x (to fix a bug with electron & wayland).

See also: logseq/logseq#6032

**Comment by webbj74** [comment]
Hmm - when running `yarn dev-electron-app` from macOS (following logseq's `develop-logseq.md`), I'm able to replicate this problem.

**Comment by piyueh** [comment]
I'm the maintainer of the AUR package `logseq-desktop-git`. Could anyone see if this plugin now works with `logseq-desktop-git`? It's working on my machine, but I don't really use this plugin, so maybe someone can do more and deeper tests.

The upstream has bumped the version of `electron` to v19 (and bumped the Logseq version to v8), so the only thing I did was to remove the patch for electron version.

**Comment by haoadoreorange** [comment]
I confirm that the plugin works with `logseq-desktop-git`, it seems the problem was indeed with the electron version.

**Comment by arnefm** [comment]
Yes, it works fine now after rebuilding Logseq. I'm now on version 0.8.1, package version 0.8.1.r21.653b72211-1. Not a plugin bug after all!

**Comment by Microeinstein** [comment]
Sorry for disappearing,
I still wanted to say I confirm it's working for me too with Logseq 0.8.8 and mentioned repackaging :+1:
![immagine](https://user-images.githubusercontent.com/16826381/197594925-7c2dc3f8-c19a-4e61-845e-707f8965a24e.png)
