### ISSUE TITLE
Widget conflicts with Paper theme (wrong z-index)

### ISSUE THREAD

**Issue by melat0nin** [ahonn/logseq-plugin-todo#15]
Great plugin!

The scrollbar of the [Paper theme](https://github.com/wirtzdan/logseq-paper-theme) conflicts with the popup widget:

![image](https://user-images.githubusercontent.com/912688/174004134-1854f64c-99d0-461e-b3c0-1119130b1cf1.png)

Just needs a z-index tweak, I think.

**Comment by ahonn** [comment]
Sorry, I have no way to reproduce. It looks normal under the Paper theme. Please update to the latest version to see if it can be reproduced.
