### ISSUE TITLE
Excellent plugin

### ISSUE THREAD

**Issue by DarthPleurotus** [ahonn/logseq-plugin-todo#16]
Not an issue, just didn't know where else to submit positive feedback. 

The documentation is a little sparse but this is a VERY good plugin. Well though out, easy to use and hard to "break" using different workflows or in combination with other plugins. In my experience, this is easily the best task-oriented Logseq plugin. Good work!

**Comment by ahonn** [comment]
Thank you. The documentation is indeed a bit sparse, and I plan to update it a bit soon (including the plugin gif). Feel free to give feedback on any other feature suggestions!
