### ISSUE TITLE
Feat: Night Mode

### ISSUE THREAD

**Issue by 23727** [ahonn/logseq-plugin-todo#18]
It would be nice to have an option to choose the color of the widget for light and dark mode in the plugin's settings.

The 'Journals Calendar' plugin does this, and it works well. 

<img width="973" alt="Screen Shot 2022-07-05 at 22 36 48" src="https://user-images.githubusercontent.com/84650530/177476472-f805b918-42a7-4782-a3e5-fe1d64ed41a6.png">

Thank you.

**Comment by ahonn** [comment]
Hi, Night Mode already supported, please update to the latest version to use.
