### ISSUE TITLE
Feature: Option to change the sort order

### ISSUE THREAD

**Issue by dcoales** [ahonn/logseq-plugin-todo#19]
At the moment it is configured to show tasks in descending scheduled date order.  Is it possible to add setting to show oldest first ?

Thanks,
David

**Comment by Oyyko** [comment]
Hello! Do we have any progress in this issue. Really need it.

**Comment by ahonn** [comment]
> Hello! Do we have any progress in this issue. Really need it.

Thanks for your feedback, I will add this feature recently.

**Comment by ahonn** [comment]
Hi  @Oyyko @dcoales,
The option to change task sort is supported for now, you can update to the latest version to try it.

If you like this plugin, feel free to show your appreciation by [buying me a coffee](https://www.buymeacoffee.com/yuexunjiang). It will motivate me to continue maintaining it.
