### ISSUE TITLE
Reading map error when opening/restarting logseq

### ISSUE THREAD

**Issue by cliffordx** [ahonn/logseq-plugin-todo#23]
<img width="397" alt="Screen_Shot_2022-09-15_at_12 37 58_AM_1663173566167_0" src="https://user-images.githubusercontent.com/7141739/190307473-b2fc01bc-109a-4a90-9294-6581bc65deea.png">

Logseq v. 0.8.7
plugin version: 1.7.0

**Comment by ahonn** [comment]
This issue has been fixed in the new version, please update it
