### ISSUE TITLE
Feature: Where to place new To-Do on journal page

### ISSUE THREAD

**Issue by dominiwe** [ahonn/logseq-plugin-todo#24]
It would be cool to be able to specify where new To-Dos are created on the current journal page when using the "*Type a task and hit enter*" feature.

For example, it could be configurable to create a `- To-Do` section at the top of the journal and then add the To-Dos as children of that.

**Comment by ahonn** [comment]
Good suggestion, I will support this feature in the near future.

**Comment by ahonn** [comment]
![yT0zG2Op@2x](https://user-images.githubusercontent.com/9718515/196631545-2a87af2f-7de1-4844-a2f0-579a37ff0c13.png)

Hi, this feature is now supported.
