### ISSUE TITLE
Page title not showing when I click on a todo

### ISSUE THREAD

**Issue by pplebel** [ahonn/logseq-plugin-todo#25]
Hi! When I click on a Todo in the list, it brings me to the page where it resides, but the page title is missing.

**Comment by ahonn** [comment]
I can't reproduce the problem, can you upload a video to let me know the details ?

**Comment by pplebel** [comment]
Hi!

Here's a video of what I am talking about

https://user-images.githubusercontent.com/16612292/194931090-53a22a6f-5584-4132-b876-b4d54bd32875.mov

**Comment by ahonn** [comment]
It looks like a change in the plugin's API caused the issue, which has now been fixed.
Please update to the latest version of the plugin.

**Comment by pplebel** [comment]
Thank you! I updated the plugin and I can confirm that it fixed the issue.
