### ISSUE TITLE
How to set the form of the "SCHEDULED" as [[yyyy-mm-dd]] instead of <yyyy-MM-dd ddd>?

### ISSUE THREAD

**Issue by KL2101** [ahonn/logseq-plugin-todo#26]
Hi there,

Can I set the form of the "SCHEDULED" as [[yyyy-mm-dd]] instead of <yyyy-MM-dd ddd>?

![20221006_Qzh4OY](https://ouyoung.oss-cn-zhangjiakou.aliyuncs.com/uPic/20221006_Qzh4OY.png!upic)

I hope to achieve when I finish a task of the past today, I want to let the "DONE TASK" as a Linked Reference of Today's Journal.

**Comment by ahonn** [comment]
It is not currently supported and this approach does not seem to be conventional.
But perhaps we could support adding the corresponding date stamp to the end when the task is completed

Like：
```
[x] completed task #[[2022-10-06]]
SCHEDULED: <2022-10-06 Thu>
```

**Comment by JasonX2140** [comment]
Thank you for your reply. 

and I think  "add the corresponding date stamp" is a good way to satisfy this functional requirement.

so, I want to know how can I set the plugin "logseq-plugin-todo" as the way you told?

Thank you very much!

**Comment by ahonn** [comment]
That feature is not support yet, I will support it ASAP.

**Comment by JasonX2140** [comment]
All right, thank you. I'm looking forward to it very much.
