### ISSUE TITLE
Duplicated tasks in Today and Anytime

### ISSUE THREAD

**Issue by KierPrev** [ahonn/logseq-plugin-todo#3]
The plugin's interface shows the same tasks repeated in "Today" and "Anytime" categories.

It surely should be showing them just once.

PS:  Thanks for creating this plugin!

**Comment by ahonn** [comment]
@KierPrev I also found this problem and have just fixed it. Please update the plugin to v1.1.2.

**Comment by KierPrev** [comment]
The duplicated tasks persist for me in v1.1.2.

Thanks!  See it tomorrow, don't worry.

**Comment by KierPrev** [comment]
Solved in 1.1.4   Many thanks :D  Amazing ❤️
