### ISSUE TITLE
Plugin doesn't follow the dark theme after loading

### ISSUE THREAD

**Issue by dmytrodubinin** [ahonn/logseq-plugin-todo#31]
OS: Fedora Linux, Flatpack package
Logseq 0.8.10
When Logseq start in dark theme (in my case with custom theme) plugin doesn't follow dark theme (start with light theme)
But if I change theme directly, plugin also change theme (light and dark)

When Logseq start with dark theme:
![image](https://user-images.githubusercontent.com/8066458/201303968-f7208635-022d-46ad-987f-c9f1554641a5.png)

When I change theme myself (working well):
![image](https://user-images.githubusercontent.com/8066458/201304160-dfde16b2-6365-4ee9-aefa-c1c9d907fb28.png)
![image](https://user-images.githubusercontent.com/8066458/201304285-7ccc697b-20b7-4501-853b-6214678056cd.png)

**Comment by ahonn** [comment]
Fixed. Thanks for your feedback

**Comment by paul-vd** [comment]
Seems like this issue is back?

**Comment by dmytrodubinin** [comment]
> Seems like this issue is back?

Yes, this issue is back

**Comment by ahonn** [comment]
@paul-vd @dmytrodubinin

Not sure why this issue is back, but I ensured that they will always be read user config for now.
Please update to the latest version.

**Comment by dmytrodubinin** [comment]
Currently reinstall plugin. The problem appear when start logseq in dark theme - plugin use light theme. But if I directly change theme, plugin update theme correctly

**Comment by dmytrodubinin** [comment]
Thanks, problem fixed!
