### ISSUE TITLE
Open task in right sidebar

### ISSUE THREAD

**Issue by foolioo** [ahonn/logseq-plugin-todo#36]
I've selected Open task in right sidebar.

![image](https://user-images.githubusercontent.com/28758375/211756581-fbf3dc71-043d-4f85-8cf2-36a783d44f89.png)

When using the Quick open hotkey it does not open the tasks in the right sidebar.
How can I open the tasks in the right sidebar (would appreciate a hotkey and a slash command if such exists)?

**Comment by ahonn** [comment]
Hi. You may have misunderstood here. In fact this means whether to show up in the right sidebar when you click on a to-do item in the plugin.

**Comment by ahonn** [comment]
There is currently no way to display the to-do list in the sidebar (maybe slash command works, but it doesn't update automatically, so I dropped this feature).
And the hotkey is just used to quickly open the panel.

**Comment by ahonn** [comment]
> open in the sidebar all the todo's without schedule


Good idea, consider supporting this feature in the near future

**Comment by ahonn** [comment]
![CleanShot 2023-02-26 at 22 17 50@2x](https://user-images.githubusercontent.com/9718515/221416143-27d3618f-3492-433d-8521-2ef8669209d1.png)

Hi, a button has been added to open all tasks in a section in the right sidebar in the new version.
