### ISSUE TITLE
Not able to install plugin

### ISSUE THREAD

**Issue by z3dd1cu55** [ahonn/logseq-plugin-todo#38]
Hi,
first of all I want to thank you for your work.

I wanted to install your plugin but logseq threw the following error:

`[Error]<logseq-todo-plugin> :release-channel-issue "invalid json response body at https://api.github.com/repos/ahonn/logseq-plugin-todo/releases/latest reason: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"]`

I am using logseq 0.8.16 (rev. [b5b1a46](https://github.com/logseq/logseq/commit/b5b1a46)) on Win10.

If you need more Information I'll be glad to provide it.

**Comment by ahonn** [comment]
I can't reproduce it here, and please try to see if the problem is still there.
From the presentation, it looks like a network issue.

**Comment by z3dd1cu55** [comment]
Thanks for your reply.
It seems like you're right. Logseq itself also isn't able to search for updates. ATM I'm connected to the internet through a VPN and proxy from my company. I'll try again on Monday in the office. There I was able to install other plugins so it should work with this one, too.
I'll close the issue if it works.

**Comment by z3dd1cu55** [comment]
Sorry for not writing back earlier.
The problem was on my site.
Your plugin is working flawlessly.
