### ISSUE TITLE
"NOW" tasks should be in Today's list rather than in Anytime list

### ISSUE THREAD

**Issue by charlyhong** [ahonn/logseq-plugin-todo#39]
I have some tasks created with keyword NOW. They are listed in the list "Anytime".
I think it makes more sense to list them in the list "Today".
Thank you.

**Comment by ahonn** [comment]
Maybe I can add optional settings for showing the NOW task in the Today section

**Comment by charlyhong** [comment]
Yes, I guess that's an acceptable option.

**Comment by ahonn** [comment]
Hi, the plugin has updated new features and added a filter to filter the task list by marker or priority. And you can set default values through defaultMarker/defaultPriority in the plugin settings. This update should meet the needs you have raised.
