### ISSUE TITLE
Feature request: universal keyboard shortcut to quick add task

### ISSUE THREAD

**Issue by rumurphy** [ahonn/logseq-plugin-todo#4]
Similar execution to Todoist or Things where from anywhere (even outside of Logseq app) can hit shortcut and Quick Add functionality is shown

**Comment by ahonn** [comment]
Thank you for the feature request!
Currently, there is no way to trigger the plugin outside of the Logseq app, but it is possible to provide shortcuts to quickly open it while in Logseq.

**Comment by thinkh** [comment]
It would be helpful already when I can quickly add a todo within Logseq. You could have a look how the shortcut functionality was implemented in this plugin https://github.com/hkgnp/logseq-quicktodo-plugin.

**Comment by ahonn** [comment]
For now, you can press `mod+shift+t` to quickly open task panel and focus the task input.
