### ISSUE TITLE
Add option to hide LATER tasks

### ISSUE THREAD

**Issue by aadilayub** [ahonn/logseq-plugin-todo#40]
I use this plugin to keep track of all the things I have to do in a week. I also have lots of LATER tasks though which I may or may not do at a future do. It'd be nice to be able to hide them.

**Comment by ahonn** [comment]
Hi, the plugin has updated new features and added a filter to filter the task list by marker or priority. And you can set default values through defaultMarker/defaultPriority in the plugin settings. This update should meet the needs you have raised.

**Comment by aadilayub** [comment]
Thank you!
