### ISSUE TITLE
Word break in the middle in the TODO list

### ISSUE THREAD

**Issue by aifreedom** [ahonn/logseq-plugin-todo#41]
See the attached screenshot. Words broken in the middle are hard to read. 

![image](https://user-images.githubusercontent.com/70373/220829212-a5c48c05-a4d3-40d6-bd13-028ee0a4f16a.png)

I think the commit that introduced the CSS class was https://github.com/ahonn/logseq-plugin-todo/commit/2968e7daa2c71fc846f714d419dbcf5a929b82ee. Removing the class `break-all` should fix it.

**Comment by ahonn** [comment]
Thank you for the digging! 
Are you happy to submit a PR?

**Comment by aifreedom** [comment]
Sure, happy to do that later this week
