### ISSUE TITLE
This error is back with v 1.16.3 "Todo list failed to render.  Can you re-index your graph and try again?"

### ISSUE THREAD

**Issue by bobmhughes** [ahonn/logseq-plugin-todo#44]
This error is back with v 1.16.3 "Todo list failed to render.  Can you re-index your graph and try again?"

Re-indexing files does not solve this issue

I reverted to the previous version so I can use the plugin in the meantime.

**Comment by ahonn** [comment]
I don't see any issues. Can you please specify the version of Logseq you're using?

**Comment by bobmhughes** [comment]
Sorry for the delay in responding.

I am using Logseq 0.8.16.



From: Yuexun Jiang ***@***.***>
Date: Wednesday, March 8, 2023 at 11:46 PM
To: ahonn/logseq-plugin-todo ***@***.***>
Cc: bobmhughes ***@***.***>, Author ***@***.***>
Subject: Re: [ahonn/logseq-plugin-todo] This error is back with v 1.16.3 "Todo list failed to render. Can you re-index your graph and try again?" (Issue #44)

I don't see any issues. Can you please specify the version of Logseq you're using?

**Comment by bobmhughes** [comment]
This error is no longer occurring with v 1.16.5.

**Comment by hezhizhen** [comment]
![Uploading Screenshot 2023-04-17 at 15.45.52.png…]()

It's appearing again.

- Logseq: 0.9.2
- Plugin: 1.17.0

**Comment by bobmhughes** [comment]
I don’t see any error messages with

  *   Logseq: 0.9.2
  *   Plugin: 1.17.0


From: Zhizhen He ***@***.***>
Date: Monday, April 17, 2023 at 12:47 AM
To: ahonn/logseq-plugin-todo ***@***.***>
Cc: bobmhughes ***@***.***>, State change ***@***.***>
Subject: Re: [ahonn/logseq-plugin-todo] This error is back with v 1.16.3 "Todo list failed to render. Can you re-index your graph and try again?" (Issue #44)

Error! Filename not specified.

It's appearing again.

  *   Logseq: 0.9.2
  *   Plugin: 1.17.0

**Comment by hezhizhen** [comment]
Is it possible that I have too many TODOs ?

**Comment by hezhizhen** [comment]
> Is it possible that I have too many TODOs ?

It seemed so.
