### ISSUE TITLE
Feat: Add new settings to allow all possible markers to selectable for filtering under "Marker:"

### ISSUE THREAD

**Issue by kwand** [ahonn/logseq-plugin-todo#48]
I have an (atypical?) workflow where I actually use all the available markers (and sort of disregard the preferred marker setting in Logseq).

It would be nice if a setting could be added where "TODO", "DOING", "LATER", and "NOW" could all be chosen under "Marker" for filtering.

Additionally, could you also add "WAITING" to be selectable as well?

(And many thanks for the awesome plugin!)

**Comment by ahonn** [comment]
I need some time to think about how to support this. What do you think about adding a setting option for custom markers?

**Comment by kwand** [comment]
>  What do you think about adding a setting option for custom markers?

That sounds good I think.

**Comment by ahonn** [comment]
@kwand 
Adding a custom Marker is already supported in the latest version v1.18, and the default is "WAITING".
You can add any Marker you want as long as they are separated by commas, e.g. "WAITING, OTHER_MARKER".

**Note that if you add a task with a custom marker to the journal page, it will not show up in `Today` section after the day, but in `Anytime`**
