### ISSUE TITLE
Bug: pop-up window position is not (relatively-)fixed

### ISSUE THREAD

**Issue by feigaoxyz** [ahonn/logseq-plugin-todo#5]
Bug report: 
1. the pop-up window position is not (relatively-)fixed, and 
2. if the logseq window width is narrow, the pop-up window is totally outside (to the left) of the main window.

![2022-04-27-102945-CleanShot-LPMQSsH0](https://user-images.githubusercontent.com/5907519/165427070-603f929e-4bca-4356-b4f1-30bcf7e33e44.png)

**Comment by ahonn** [comment]
The issue has been fixed. Please update to the latest version.
