### ISSUE TITLE
v1.17.0 doesn't match theme

### ISSUE THREAD

**Issue by abhilesh** [ahonn/logseq-plugin-todo#53]
<img width="900" alt="Screenshot 2023-04-13 at 15 56 31" src="https://user-images.githubusercontent.com/2447878/231801246-21c9ae55-1f1b-43d1-8a92-8f2bfe7805fa.png">

**Comment by ahonn** [comment]
![image](https://user-images.githubusercontent.com/9718515/233252885-874d9fcc-9286-4d09-ba6a-e20c29a41797.png)
The plugin can't get the color of the current theme, you can set the dark mode color yourself in the plugin settings

**Comment by abhilesh** [comment]
Thanks a lot for pointing me towards this! Manually setting the colors works!
