### ISSUE TITLE
What is the syntax for todo items that plugin is looking for? (priority, dates, anything else?)

### ISSUE THREAD

**Issue by prb01-work** [ahonn/logseq-plugin-todo#62]
Hi,

Firstly, thanks for the plugin! It has converted me from Obsidian to Logseq so I can have all my notes & tasks in one place.

To my Q, I notice that you can filter by priority in the task list (A, B, C etc.) - what are all the syntaxes that get picked up by the plugin? 

For example, in a previous todo app, I would write something like this:

> (C) Explore page builder: grapesjs due:2023-12-30 @coding
 
 Where,
 **(C)** is the priority
 **due:YYYY-MM-DD** is the due date
 **@text** is an additional tag

I'm assuming priority is possible but I can't figure out how I need to write it. What others are possible?

Thanks!

**Comment by ahonn** [comment]
Logseq ships with some default priorities, You can use /A, /B or /C to set priorities, or you can manually enter [#A], [#B] or [#C]. This plugin is based on this to do priority filtering.
