### ISSUE TITLE
Leave task input in focus after adding task

### ISSUE THREAD

**Issue by NicolasCwy** [ahonn/logseq-plugin-todo#68]
Hi currently to add multiple tasks I would have to open the task panel and manually click on the task input field. I could also use the keybinds to close and reopen the task panel to refocus the task input field.

Would it be possible to leave the task input field in focus till I want to close the panel?

**Comment by ahonn** [comment]
Thanks for your feedback. The reason for this situation is that the Plugin API of Logseq will snatch focus after updating the page content. Now I have implemented a hack to solve it.

In the latest version, you can continuously create new tasks while keeping the panel open. If you have any other questions, just let me know.

If you like this plugin, feel free to show your appreciation by [buying me a coffee](https://www.buymeacoffee.com/yuexunjiang). It will motivate me to continue maintaining it.

**Comment by NicolasCwy** [comment]
Hi ahonn, just got the chance to try this out, it doesn't seem like the field is focused although the todo panel remains open, I have to manually click on it
