### ISSUE TITLE
Feature request: ignore list for sites with TODOs

### ISSUE THREAD

**Issue by cxt666** [ahonn/logseq-plugin-todo#72]
Currently, I use templates for different daily tasks. the TODO topics in there are always listed in the TODO-list of course, but it does not make sense:

Question: is it possible to add a "ignore list" option to add page names which should be ignored for ingest into the TODO-list?

**Comment by ahonn** [comment]
see https://github.com/ahonn/logseq-plugin-todo/issues/8
