### ISSUE TITLE
How to use todo-ignore

### ISSUE THREAD

**Issue by mifas** [ahonn/logseq-plugin-todo#8]
Hi, I'm new to logseq, wanted to know how to use `todo-ignore`

**Comment by ahonn** [comment]
Add add `todo-ignore:: true` to the first line of the page, then to-do items in the page will not be displayed in the plugin

**Comment by mifas** [comment]
Got it, Thank you!

**Comment by wei150mail7837** [comment]
1,“todo-ignore"some time works but sometime dosen't.
2,how can i use it to ignore only one block,such as there is four blocks of todo in one page and i want to ignore only one
3,how can i take it in the template
4,whether the "true"can be change to other,such as "today" or "pagename"?
