### ISSUE TITLE
Feature Request - Add Option to Show Future Tasks in the next 'n' Days

### ISSUE THREAD

**Issue by adxsoft** [ahonn/logseq-plugin-todo#9]
Nice work .. very useful plugin. It would be even more powerful if you could view future tasks for a chosen period so the display would look like this (assuming today is Wednesday 1st June 2022  and there are two future todo's and there is a setting for 'Future period in days' set to 14 days)

**Today**
[ ] task for today

**Next 14 days**
[ ] put out the garbage on Friday
2022-06-03

[ ] doctors appointment 3pm next Monday
2022-06-06

**Scheduled**
etc etc

The query for the future period would be something like this

```
{:title "📅 NEXT 14 DAYS"
    :query [:find (pull ?h [*])
            :in $ ?start ?next
            :where
            [?h :block/marker ?marker]
            [(contains? #{"NOW" "LATER" "TODO"} ?marker)]
            [?h :block/page ?p]
            [?p :block/journal? true]
            [?p :block/journal-day ?d]
            [(> ?d ?start)]
            [(< ?d ?next)]]
    :inputs [:today :14d-after]
    :collapsed? false}]}
```

**Comment by ahonn** [comment]
![image](https://user-images.githubusercontent.com/9718515/211185379-78e5b6e9-8b03-42cb-8977-e32377d4da42.png)

This feature is now supported, please update to the latest version and turn on this switch.
